# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

bandpass_filter:
  _target_: emg2qwerty.transforms.ForEach 
  transform:
    _target_: emg2qwerty.transforms.BandpassFiltering
    lowcut: 20.0
    highcut: 450.0
    fs: 2000.0
    order: 4
    rs: 20

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120  # Max 60ms jitter for 2kHz EMG

hilbert_envelope:
  _target_: emg2qwerty.transforms.ForEach
  transform:
    _target_: emg2qwerty.transforms.HilbertEnvelopeTransform
    smooth: true  
    cutoff_freq: 1.0  
    fs: 2000  
    normalize: true
    
logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16  # Downsamples from 2kHz to 125Hz

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25  # Max 200ms per time mask for 125Hz spectrogram
  n_freq_masks: 2
  freq_mask_param: 4
  
mel_stft:
  _target_: emg2qwerty.transforms.ForEach 
  transform:
    _target_: emg2qwerty.transforms.MelSTFTTransform
    n_fft: 64
    hop_length: 16
    n_mels: 40
  
random_crop:
  _target_: emg2qwerty.transforms.RandomCrop
  crop_size: 40
  

transforms:
  train:
    - ${to_tensor}
    - ${band_rotation}
    - ${temporal_jitter}
    - ${logspec}
    - ${specaug}

  val:
    - ${to_tensor}
    - ${logspec}

  test: ${transforms.val}
